apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-plane-secret-sync
  namespace: operator-secret-sync
  labels:
    app.kubernetes.io/name: operator-secret-sync
    app.kubernetes.io/part-of: operator-plane
automountServiceAccountToken: true
