apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: smoke-whoami
  labels:
    app.kubernetes.io/name: whoami
    app.kubernetes.io/part-of: family-infra-traefik-smoke-test
spec:
  selector:
    app.kubernetes.io/name: whoami
  ports:
    - name: http
      port: 80
      targetPort: 80
