tls:
  certificates:
    - certFile: /pki/issued/auth.internal/tls.crt
      keyFile: /pki/issued/auth.internal/tls.key
    - certFile: /pki/issued/whoami.internal/tls.crt
      keyFile: /pki/issued/whoami.internal/tls.key
    - certFile: /pki/issued/files.internal/tls.crt
      keyFile: /pki/issued/files.internal/tls.key

