services:
  vault:
    image: hashicorp/vault:1.19
    container_name: vault
    restart: unless-stopped
    ports:
      - "127.0.0.1:8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./config/vault.hcl:/vault/config/vault.hcl:ro
      - ./file:/vault/file
      - ./logs:/vault/logs
    command: vault server -config=/vault/config/vault.hcl
    networks:
      - proxy

networks:
  proxy:
    external: true