global:
  checkNewVersion: false
  sendAnonymousUsage: false

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

api:
  dashboard: true
  insecure: false

logs:
  access:
    enabled: true
