http:
  routers:
    passwords-internal:
      rule: "Host(`passwords.internal`)"
      entryPoints:
        - websecure
      tls: {}
      service: passwords-internal-svc

  services:
    passwords-internal-svc:
      loadBalancer:
        passHostHeader: true
        serversTransport: passwords-internal-ca
        servers:
          - url: "https://vaultwarden:443"

  serversTransports:
    passwords-internal-ca:
      serverName: "passwords.internal"
      rootCAs:
        - "/pki/ca/internal-ca.crt"