tls:
  certificates:
    - certFile: /pki/issued/auth.internal/tls.crt
      keyFile: /pki/issued/auth.internal/tls.key
    - certFile: /pki/issued/whoami.internal/tls.crt
      keyFile: /pki/issued/whoami.internal/tls.key
    - certFile: /pki/issued/files.internal/tls.crt
      keyFile: /pki/issued/files.internal/tls.key
    - certFile: /pki/issued/office.internal/tls.crt
      keyFile: /pki/issued/office.internal/tls.key
    - certFile: /pki/issued/passwords.internal/tls.crt
      keyFile: /pki/issued/passwords.internal/tls.key
    - certFile: /pki/issued/hr.internal/tls.crt
      keyFile: /pki/issued/hr.internal/tls.key
    - certFile: /pki/issued/identity.internal/tls.crt
      keyFile: /pki/issued/identity.internal/tls.key
