http:
  routers:
    whoami:
      rule: "Host(`whoami.internal`)"
      entryPoints:
        - websecure
      tls: {}
      service: whoami-svc
      middlewares:
        - secure-headers@file

  services:
    whoami-svc:
      loadBalancer:
        servers:
          - url: "http://whoami:80"