schemaVersion: 1

tenant:
  name: family-infra
  node: family-infra-01

components:
  openbao:
    release: 1

storage:
  openbao:
    class: local-path
    size: 1Gi

pki:
  root:
    ttl: 87600h
  issuing:
    ttl: 26280h
  leaf:
    defaultTtl: 2160h

openbao:
  canonicalDnsName: vault.internal
  namespace: openbao-family-infra
  statefulSetName: openbao
  serviceAccountName: openbao
  configMapName: openbao-bootstrap-config
  dataVolumeName: openbao-raft
  transit:
    address: https://openbao-global.openbao-operator.svc.cluster.local:8200
    keyName: family-infra-01-autounseal
    mountPath: transit/
    tlsServerName: openbao-global.openbao-operator.svc.cluster.local
    caBundleConfigMapName: operator-ca-bundle
    caBundleKey: ca.crt
    caBundleMountPath: /openbao/tls/operator-ca-bundle.pem
    tokenSecretName: openbao-transit-autounseal
    tokenSecretKey: token

recovery:
  shares: 3
  threshold: 2
